version: 2
jobs:
  build_1st:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            sudo pip install django-rest-assured
            sudo pip install -U pytest
            sudo pip install pytest-html
      - run:
          name: Running tests
          command: |
            cd restassured_1st
            pytest -sv --html report/report.html
      - store_artifacts:
          path: restassured_1st/report/
          destination: report_1st
workflows:
  version: 2
  workflow:
    jobs:
    - build_1st